// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Design_Rglass : Design {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Reinforced glass";
			this.id = "rglass";
			this.build_type = 4;
			this.materials = new ByTable().Set( "$metal", 1000 ).Set( "$glass", 2000 );
			this.build_path = typeof(Obj_Item_Stack_Sheet_Rglass);
			this.category = new ByTable(new object [] { "initial", "Construction" });
			this.maxstack = 50;
		}

	}

}