// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Reagent_Consumable_SpaceUp : Reagent_Consumable {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Space-Up";
			this.id = "space_up";
			this.description = "Tastes like a hull breach in your mouth.";
			this.color = "#00FF00";
		}

		// Function from file: drink_reagents.dm
		public override bool on_mob_life( dynamic M = null ) {
			
			if ( Convert.ToDouble( M.bodytemperature ) > 310 ) {
				M.bodytemperature = Num13.MaxInt( 310, Convert.ToInt32( M.bodytemperature - 12 ) );
			}
			base.on_mob_life( (object)(M) );
			return false;
		}

	}

}