// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class RoundEventControl_Presents : RoundEventControl {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Presents under Trees (Christmas)";
			this.holidayID = "Christmas";
			this.typepath = typeof(RoundEvent_Presents);
			this.weight = -1;
			this.max_occurrences = 1;
			this.earliest_start = 0;
		}

	}

}