// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class RoundEventControl_ShuttleLoan : RoundEventControl {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Shuttle loan";
			this.typepath = typeof(RoundEvent_ShuttleLoan);
			this.max_occurrences = 1;
			this.earliest_start = 4000;
		}

	}

}