// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class SpellbookEntry_Item_Soulstones : SpellbookEntry_Item {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Six Soul Stone Shards and the spell Artificer";
			this.desc = "Soul Stone Shards are ancient tools capable of capturing and harnessing the spirits of the dead and dying. The spell Artificer allows you to create arcane machines for the captured souls to pilot.";
			this.item_path = typeof(Obj_Item_Weapon_Storage_Belt_Soulstone_Full);
			this.log_name = "SS";
			this.category = "Assistance";
		}

		// Function from file: spellbook.dm
		public override bool Buy( Mob user = null, Obj_Item_Weapon_Spellbook book = null ) {
			bool _default = false;

			_default = base.Buy( user, book );

			if ( _default ) {
				user.mind.AddSpell( new Obj_Effect_ProcHolder_Spell_AoeTurf_Conjure_Construct( null ) );
			}
			return _default;
		}

	}

}