// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class SpriteAccessory_Snouts_Sharplight : SpriteAccessory_Snouts {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Sharp + Light";
			this.icon_state = "sharplight";
		}

	}

}