// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class SpriteAccessory_Hair_Cut : SpriteAccessory_Hair {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Cut Hair";
			this.icon_state = "hair_c";
		}

	}

}