// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class UplinkItem_Dangerous_Carbine_Unrestricted : UplinkItem_Dangerous_Carbine {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.item = typeof(Obj_Item_Weapon_Gun_Projectile_Automatic_M90_Unrestricted);
			this.include_modes = new ByTable(new object [] { typeof(GameMode_Gang) });
		}

	}

}