// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class UplinkItem_Dangerous_Pistol : UplinkItem_Dangerous {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Stechkin Pistol";
			this.desc = "A small, easily concealable handgun that uses 10mm auto rounds in 8-round magazines and is compatible with suppressors.";
			this.item = typeof(Obj_Item_Weapon_Gun_Projectile_Automatic_Pistol);
			this.cost = 9;
		}

	}

}