// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class ChemicalReaction_CarpPheromones : ChemicalReaction {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Carp pheromones";
			this.id = "carppheromones";
			this.result = "carppheromones";
			this.required_reagents = new ByTable().Set( "carpotoxin", 1 ).Set( "leporazine", 1 ).Set( "carbon", 1 );
			this.result_amount = 3;
		}

	}

}