// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class ChemicalReaction_Espresso : ChemicalReaction {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Espresso";
			this.id = "espresso";
			this.result = "espresso";
			this.required_reagents = new ByTable().Set( "coffee", 1 ).Set( "water", 1 );
			this.result_amount = 2;
		}

	}

}