// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class ChemicalReaction_Peptobismol : ChemicalReaction {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Peptobismol";
			this.id = "peptobismol";
			this.result = "peptobismol";
			this.required_reagents = new ByTable().Set( "anti_toxin", 1 ).Set( "discount", 1 );
			this.result_amount = 2;
		}

	}

}