// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Coords : Game_Data {

		public double? x_pos = null;
		public double? y_pos = null;
		public dynamic z_pos = null;

		// Function from file: unsorted.dm
		public Coords ( double? x = null, double? y = null, dynamic z = null ) {
			// Warning: Super call was HERE! If anything above HERE is needed by the super call, it might break!;
			this.x_pos = x;
			this.y_pos = y;
			this.z_pos = z;
			return;
		}

		// Function from file: unsorted.dm
		public Coords add( Coords C = null ) {
			Coords CR = null;

			CR = new Coords( ( this.x_pos ??0) + ( C.x_pos ??0), ( this.y_pos ??0) + ( C.y_pos ??0), this.z_pos + C.z_pos );
			return CR;
		}

		// Function from file: unsorted.dm
		public Coords subtract( Coords C = null ) {
			Coords CR = null;

			CR = new Coords( ( this.x_pos ??0) - ( C.x_pos ??0), ( this.y_pos ??0) - ( C.y_pos ??0), this.z_pos - C.z_pos );
			return CR;
		}

		// Function from file: unsorted.dm
		public bool equal_to( Coords C = null ) {
			
			if ( this.x_pos == C.x_pos && this.y_pos == C.y_pos && this.z_pos == C.z_pos ) {
				return true;
			}
			return false;
		}

	}

}