// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Design_PodCore : Design {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Spacepod Core";
			this.desc = "Allows for the construction of a spacepod core system, made up of the engine and life support systems.";
			this.id = "podcore";
			this.build_type = 32;
			this.req_tech = new ByTable().Set( "materials", 4 ).Set( "engineering", 3 ).Set( "plasmatech", 3 ).Set( "bluespace", 2 );
			this.build_path = typeof(Obj_Item_PodParts_Core);
			this.category = "Pod_Parts";
			this.materials = new ByTable().Set( "$iron", 5000 ).Set( "$uranium", 1000 ).Set( "$plasma", 5000 );
		}

	}

}