// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Design_BorgServiceUpgrade : Design {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "service module board";
			this.desc = "Used to give a service cyborg cooking tools.";
			this.id = "borg_service_module";
			this.req_tech = new ByTable().Set( "biotech", 2 ).Set( "engineering", 3 ).Set( "programming", 2 );
			this.build_type = 16;
			this.materials = new ByTable().Set( "$iron", 60000 ).Set( "$glass", 10000 );
			this.build_path = typeof(Obj_Item_Borg_Upgrade_Service);
			this.category = "Robotic_Upgrade_Modules";
		}

	}

}