// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Design_Odysseus_Chassis : Design_Odysseus {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Exosuit Structure (Odysseus chassis)";
			this.desc = "Used to build a Odysseus chassis.";
			this.id = "odysseus_chassis";
			this.req_tech = new ByTable().Set( "biotech", 1 );
			this.build_type = 16;
			this.build_path = typeof(Obj_Item_MechaParts_Chassis_Odysseus);
			this.category = "Odysseus";
			this.materials = new ByTable().Set( "$iron", 20000 );
		}

	}

}