// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Disease2_Effect_Lantern : Disease2_Effect {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Lantern Syndrome";
			this.stage = 2;
		}

		// Function from file: effect.dm
		public override bool activate( Mob_Living mob = null, bool multiplier = false ) {
			mob.set_light( 4 );
			GlobalFuncs.to_chat( mob, "<span class = 'notice'>You are glowing!</span>" );
			return false;
		}

	}

}