// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Dna_Gene_Basic_GrantSpell_Hulk : Dna_Gene_Basic_GrantSpell {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Hulk";
			this.desc = "Allows the subject to become the motherfucking Hulk.";
			this.activation_messages = new ByTable(new object [] { "Your muscles hurt." });
			this.deactivation_messages = new ByTable(new object [] { "Your muscles quit tensing." });
			this.drug_activation_messages = new ByTable(new object [] { "You feel strong! You must've been working out lately." });
			this.drug_deactivation_messages = new ByTable(new object [] { "You return to your old lifestyle." });
			this.flags = 2;
			this.spelltype = typeof(Spell_Targeted_Genetic_Hulk);
		}

		// Function from file: vg_powers.dm
		public Dna_Gene_Basic_GrantSpell_Hulk (  ) {
			// Warning: Super call was HERE! If anything above HERE is needed by the super call, it might break!;
			this.block = GlobalVars.HULKBLOCK;
			return;
		}

		// Function from file: vg_powers.dm
		public override void OnMobLife( Mob_Living M = null ) {
			bool timeleft = false;

			
			if ( !( M is Mob_Living_Carbon_Human ) ) {
				return;
			}

			if ( M.mutations.Contains( 4 ) ) {
				timeleft = Lang13.Bool( ((dynamic)M).hulk_time - Game13.time );

				if ( Convert.ToDouble( M.health ) <= 25 || ( timeleft ?1:0) <= 0 ) {
					((dynamic)M).hulk_time = 0;
					M.mutations.Remove( 4 );
					M.update_mutations();
					((Mob_Living_Carbon_Human)M).update_body();
					GlobalFuncs.to_chat( M, "<span class='warning'>You suddenly feel very weak.</span>" );
					M.Weaken( 3 );
					M.emote( "collapse" );
				}
			}
			return;
		}

		// Function from file: vg_powers.dm
		public override dynamic OnDrawUnderlays( Mob_Living_Carbon_Human M = null, string g = null, string fat = null ) {
			
			if ( M.mutations.Contains( 4 ) ) {
				
				if ( Lang13.Bool( fat ) ) {
					return "hulk_" + fat + "_s";
				} else {
					return "hulk_" + g + "_s";
				}
			}
			return 0;
		}

		// Function from file: vg_powers.dm
		public override bool can_activate( dynamic M = null, bool? flags = null ) {
			
			if ( Lang13.Bool( M.mutations.Contains( 110 ) ) ) {
				return false;
			}
			return base.can_activate( (object)(M), flags );
		}

	}

}