// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Faction_Syndicate_Donk : Faction_Syndicate {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Donk Corporation";
			this.desc = "<b>Donk.co</b> is led by a group of ex-pirates, who used to be at a state of all-out war against Waffle.co because of an obscure political scandal, but have recently come to a war limitation. They now consist of a series of colonial governments and companies. They were the first to officially begin confrontations against Nanotrasen because of an incident where Nanotrasen purposely swindled them out of a fortune, sending their controlled colonies into a terrible poverty. Their missions against Nanotrasen revolve around stealing valuables and kidnapping and executing key personnel, ransoming their lives for money. They merged with a splinter-cell of Waffle.co who wanted to end hostilities and formed the Gorlex Marauders.";
			this.alliances = new ByTable(new object [] { "Gorlex Marauders" });
			this.friendly_identification = 2;
			this.operative_notes = "Most other syndicate operatives are not to be trusted, except fellow Donk members and members of the Gorlex Marauders. We do not approve of mindless killing of innocent workers; \"get in, get done, get out\" is our motto. Members of Waffle.co are to be killed on sight; they are not allowed to be on the station while we're around.";
		}

	}

}