// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Objective_Heist_Kidnap : Objective_Heist {

		public Objective_Heist_Kidnap ( string text = null ) : base( text ) {
			
		}

		// Function from file: objectives.dm
		public override dynamic check_completion(  ) {
			dynamic end_area = null;

			
			if ( Lang13.Bool( this.target ) ) {
				
				if ( this.target.current == null || Convert.ToInt32( this.target.current.stat ) == 2 ) {
					return GlobalVars.FALSE;
				}
				end_area = GlobalFuncs.get_area_master( Lang13.FindObj( typeof(Zone_Shuttle_Vox_Station) ) );

				if ( GlobalFuncs.get_area_master( this.target.current ) != end_area ) {
					return GlobalVars.FALSE;
				}
				return GlobalVars.TRUE;
			}
			return null;
		}

		// Function from file: objectives.dm
		public override dynamic choose_target(  ) {
			ByTable roles = null;
			dynamic role = null;

			roles = new ByTable(new object [] { "Chief Engineer", "Research Director", "Roboticist", "Chemist", "Station Engineer" });

			foreach (dynamic _a in Lang13.Enumerate( GlobalFuncs.shuffle( roles ) )) {
				role = _a;
				
				this.find_target_by_role( role );

				if ( Lang13.Bool( this.target ) ) {
					break;
				}
			}

			if ( this.target == null ) {
				this.find_target();
			}

			if ( Lang13.Bool( this.target ) ) {
				this.explanation_text = "The Shoal has a need for " + this.target.current.real_name + ", the " + this.target.assigned_role + ". Take them alive.";
			} else {
				this.explanation_text = "Free Objective";
			}
			return this.target;
		}

	}

}