// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Poster_Bay8 : Poster {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.icon_state = "bsposter8";
			this.name = "Pinup Girl Cindy";
			this.desc = "This particular one is of Nanotrasen's PR girl, Cindy, in a particularly feminine pose.";
		}

	}

}