// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Poster_Tg9 : Poster {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Missing Gloves";
			this.desc = "This poster is about the uproar that followed Nanotrasen's financial cuts towards insulated-glove purchases.";
			this.icon_state = "poster9";
		}

	}

}