// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Reagent_Glycerol : Reagent {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Glycerol";
			this.id = "glycerol";
			this.description = "Glycerol is a simple polyol compound. Glycerol is sweet-tasting and of low toxicity.";
			this.reagent_state = 2;
			this.color = "#808080";
			this.custom_metabolism = 0.01;
		}

	}

}