// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Reagent_Drink_Nothing : Reagent_Drink {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Nothing";
			this.id = "nothing";
			this.description = "Absolutely nothing.";
		}

	}

}