// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Reagent_Ethanol_Deadrum_Neurotoxin : Reagent_Ethanol_Deadrum {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Neurotoxin";
			this.id = "neurotoxin";
			this.description = "A strong neurotoxin that puts the subject into a death-like state.";
			this.color = "#2E2E61";
		}

		// Function from file: Chemistry-Reagents.dm
		public override bool on_mob_life( Mob_Living M = null, int? alien = null ) {
			
			if ( base.on_mob_life( M, alien ) ) {
				return true;
			}
			M.adjustOxyLoss( 1 );
			M.weakened = Num13.MaxInt( ((int)( M.weakened )), 15 );
			M.silent = Num13.MaxInt( M.silent, 15 );
			return false;
		}

	}

}