// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Reagent_Drink_Tea_Greentea : Reagent_Drink_Tea {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Green Tea";
			this.id = "greentea";
			this.description = "Delicious green tea.";
		}

	}

}