// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Reagent_Drink_Cold : Reagent_Drink {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Cold drink";
			this.adj_temp = -5;
		}

	}

}