// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Reagent_Ethanol_Deadrum_RedMead : Reagent_Ethanol_Deadrum {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Red Mead";
			this.id = "red_mead";
			this.description = "The true Viking drink! Even though it has a strange red color.";
		}

	}

}