// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Reagent_Irradiatedbeans : Reagent {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Irradiated Beans";
			this.id = "irradiatedbeans";
			this.description = "You can almost taste the lead sheet behind it!";
			this.reagent_state = 2;
			this.color = "#6F884F";
		}

	}

}