// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Reagent_Ethanol_Deadrum_Amasec : Reagent_Ethanol_Deadrum {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Amasec";
			this.id = "amasec";
			this.description = "Official drink of the Imperium.";
		}

		// Function from file: Chemistry-Reagents.dm
		public override bool on_mob_life( Mob_Living M = null, int? alien = null ) {
			
			if ( base.on_mob_life( M, alien ) ) {
				return true;
			}
			M.stunned = 4;
			return false;
		}

	}

}