// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Recipe_Herbsalad : Recipe {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.items = new ByTable(new object [] { 
				typeof(Obj_Item_Weapon_ReagentContainers_Food_Snacks_Grown_Ambrosiavulgaris), 
				typeof(Obj_Item_Weapon_ReagentContainers_Food_Snacks_Grown_Ambrosiavulgaris), 
				typeof(Obj_Item_Weapon_ReagentContainers_Food_Snacks_Grown_Ambrosiavulgaris), 
				typeof(Obj_Item_Weapon_ReagentContainers_Food_Snacks_Grown_Apple)
			 });
			this.result = typeof(Obj_Item_Weapon_ReagentContainers_Food_Snacks_Herbsalad);
		}

		// Function from file: recipes_microwave.dm
		public override dynamic make_food( Obj_Machinery_Microwave container = null ) {
			dynamic being_cooked = null;

			being_cooked = base.make_food( container );
			((Reagents)being_cooked.reagents).del_reagent( "toxin" );
			return being_cooked;
		}

	}

}