// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Recipe_Sweetsundaeramen : Recipe {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.items = new ByTable(new object [] { 
				typeof(Obj_Item_Weapon_ReagentContainers_Food_Snacks_Sundaeramen), 
				typeof(Obj_Item_Weapon_ReagentContainers_Food_Snacks_Ricepudding), 
				typeof(Obj_Item_Weapon_ReagentContainers_Food_Snacks_Gigapuddi), 
				typeof(Obj_Item_Weapon_ReagentContainers_Food_Snacks_Donkpocket)
			 });
			this.result = typeof(Obj_Item_Weapon_ReagentContainers_Food_Snacks_Sweetsundaeramen);
		}

	}

}