// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Recipe_Eggplantsushi : Recipe {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.reagents = new ByTable().Set( "rice", 10 ).Set( "vinegar", 2 );
			this.items = new ByTable(new object [] { typeof(Obj_Item_Weapon_ReagentContainers_Food_Snacks_Grown_Eggplant), typeof(Obj_Item_Weapon_ReagentContainers_Food_Snacks_Grown_Chili) });
			this.result = typeof(Obj_Item_Weapon_ReagentContainers_Food_Snacks_Eggplantsushi);
		}

	}

}