// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class ScriptError : Game_Data {

		public dynamic message = null;

		// Function from file: Errors.dm
		public ScriptError ( dynamic msg = null ) {
			
			if ( Lang13.Bool( msg ) ) {
				this.message = msg;
			}
			return;
		}

	}

}