// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class SelectionSchematic_AirlockSchematic_GlassSec : SelectionSchematic_AirlockSchematic {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "ÿGlass Security Airlock";
			this.build_type = typeof(Obj_Machinery_Door_Airlock_GlassSecurity);
			this.icon = "icons/obj/doors/Doorsecglass.dmi";
		}

		public SelectionSchematic_AirlockSchematic_GlassSec ( RcdSchematic_ConAirlock master = null ) : base( master ) {
			
		}

	}

}