// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Spell_AoeTurf_Boo : Spell_AoeTurf {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Boo!";
			this.desc = "Fuck with the living.";
			this.spell_flags = 17;
			this.school = "transmutation";
			this.charge_max = 600;
			this.invocation = "";
			this.range = 1;
			this.override_base = "grey";
			this.hud_state = "boo";
		}

		// Function from file: spells.dm
		public override bool cast( ByTable targets = null, Mob user = null ) {
			dynamic T = null;
			Ent_Static A = null;

			
			foreach (dynamic _b in Lang13.Enumerate( targets )) {
				T = _b;
				

				foreach (dynamic _a in Lang13.Enumerate( T.contents, typeof(Ent_Static) )) {
					A = _a;
					
					A.spook();
				}
			}
			return false;
		}

	}

}