// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Spell_AoeTurf_Conjure_Forcewall : Spell_AoeTurf_Conjure {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Forcewall";
			this.desc = "Create a wall of pure energy at your location.";
			this.summon_type = new ByTable(new object [] { typeof(Obj_Effect_Forcefield) });
			this.duration = 300;
			this.spell_flags = 0;
			this.hud_state = "wiz_shield";
		}

	}

}