// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class SpriteAccessory_Hair_Crew : SpriteAccessory_Hair {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Crewcut";
			this.icon_state = "hair_crewcut";
			this.gender = "male";
		}

	}

}