// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class SurgeryStep_FixDeadTissue : SurgeryStep {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.priority = 2;
			this.allowed_tools = new ByTable().Set( typeof(Obj_Item_Weapon_Scalpel), 100 ).Set( typeof(Obj_Item_Weapon_Kitchen_Utensil_Knife_Large), 75 ).Set( typeof(Obj_Item_Weapon_Shard), 50 );
			this.can_infect = true;
			this.blood_level = 1;
			this.min_duration = 110;
			this.max_duration = 160;
		}

		// Function from file: other.dm
		public override bool? fail_step( dynamic user = null, dynamic target = null, string target_zone = null, Obj_Item tool = null, dynamic surgery = null ) {
			Organ_External affected = null;

			affected = ((Mob_Living_Carbon_Human)target).get_organ( target_zone );
			((Ent_Static)user).visible_message( new Txt( "<span class='warning'>" ).item( user ).str( "'s hand slips, slicing an artery inside " ).item( target ).str( "'s " ).item( affected.display_name ).str( " with " ).the( tool ).item().str( "!</span>" ).ToString(), new Txt( "<span class='warning'>Your hand slips, slicing an artery inside " ).item( target ).str( "'s " ).item( affected.display_name ).str( " with " ).the( tool ).item().str( "!</span>" ).ToString() );
			affected.createwound( "cut", 20 );
			return null;
		}

		// Function from file: other.dm
		public override bool end_step( dynamic user = null, dynamic target = null, string target_zone = null, Obj_Item tool = null, dynamic surgery = null ) {
			dynamic affected = null;

			affected = ((Mob_Living_Carbon_Human)target).get_organ( target_zone );
			((Ent_Static)user).visible_message( new Txt( "<span class='notice'>" ).item( user ).str( " has cut away necrotic tissue in " ).item( target ).str( "'s " ).item( affected.display_name ).str( " with " ).the( tool ).item().str( ".</span>" ).ToString(), new Txt( "<span class='notice'>You have cut away necrotic tissue in " ).item( target ).str( "'s " ).item( affected.display_name ).str( " with " ).the( tool ).item().str( ".</span>" ).ToString() );
			affected.open = 3;
			return false;
		}

		// Function from file: other.dm
		public override bool begin_step( dynamic user = null, dynamic target = null, string target_zone = null, Obj_Item tool = null, dynamic surgery = null ) {
			dynamic affected = null;

			affected = ((Mob_Living_Carbon_Human)target).get_organ( target_zone );
			((Ent_Static)user).visible_message( new Txt().item( user ).str( " starts cutting away necrotic tissue in " ).item( target ).str( "'s " ).item( affected.display_name ).str( " with " ).the( tool ).item().str( "." ).ToString(), new Txt( "You start cutting away necrotic tissue in " ).item( target ).str( "'s " ).item( affected.display_name ).str( " with " ).the( tool ).item().str( "." ).ToString() );
			((Mob_Living_Carbon_Human)target).custom_pain( "The pain in " + affected.display_name + " is unbearable!", true );
			base.begin_step( (object)(user), (object)(target), target_zone, tool, (object)(surgery) );
			return false;
		}

		// Function from file: other.dm
		public override int can_use( dynamic user = null, dynamic target = null, string target_zone = null, Obj_Item tool = null ) {
			dynamic affected = null;

			
			if ( !GlobalFuncs.hasorgans( target ) ) {
				return 0;
			}

			if ( target_zone == "mouth" || target_zone == "eyes" ) {
				return 0;
			}
			affected = ((Mob_Living_Carbon_Human)target).get_organ( target_zone );
			return Convert.ToDouble( affected.open ) >= 2 && Lang13.Bool( affected.status & 1024 ) ?1:0;
		}

		// Function from file: other.dm
		public override bool tool_quality( Obj_Item tool = null ) {
			bool _default = false;

			_default = base.tool_quality( tool );

			if ( !Lang13.Bool( tool.is_sharp() ) ) {
				return false;
			}
			return _default;
		}

	}

}