// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Symptom_WeightLoss : Symptom {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Weight Loss";
			this.stealth = -3;
			this.resistance = -2;
			this.stage_speed = -2;
			this.transmittable = -2;
			this.level = 3;
		}

		// Function from file: weight.dm
		public override void Activate( Disease_Advance A = null ) {
			dynamic M = null;

			base.Activate( A );

			if ( Rand13.PercentChance( GlobalVars.SYMPTOM_ACTIVATION_PROB ) ) {
				M = A.affected_mob;

				switch ((int?)( A.stage )) {
					case 1:
					case 2:
					case 3:
					case 4:
						GlobalFuncs.to_chat( M, "<span class='notice'>" + Rand13.Pick(new object [] { "You feel hungry.", "You crave for food." }) + "</span>" );
						break;
					default:
						GlobalFuncs.to_chat( M, "<span class='notice'>Your stomach rumbles.</span>" );
						M.overeatduration = Num13.MaxInt( M.overeatduration - 100, 0 );
						M.nutrition = Num13.MaxInt( ((int)( M.nutrition - 100 )), 0 );
						break;
				}
			}
			return;
		}

	}

}