// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Tech_Combat : Tech {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Combat Systems Research";
			this.desc = "The development of offensive and defensive systems.";
			this.id = "combat";
			this.goal_level = 5;
			this.max_level = 6;
		}

	}

}