// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Unlockable_Borer_ChemUnlock_Peridaxon : Unlockable_Borer_ChemUnlock {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.id = "peridaxon";
			this.name = "Peridaxon Secretion";
			this.desc = "Learn how to synthesize peridaxon.";
			this.cost = 200;
			this.time = 1200;
			this.chem_type = typeof(BorerChem_Unlockable_Peridaxon);
		}

	}

}