// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class UplinkItem_Jobspecific_Ambrosiacruciatus : UplinkItem_Jobspecific {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Ambrosia Cruciatus Seeds";
			this.desc = "Part of the notorious Ambrosia family, this species is nearly indistinguishable from Ambrosia Vulgaris- but its' branches contain a revolting toxin. Eight units are enough to drive victims insane after a three-minute delay.";
			this.item = typeof(Obj_Item_Seeds_Ambrosiacruciatusseed);
			this.cost = 2;
			this.job = new ByTable(new object [] { "Botanist" });
		}

	}

}