// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class UplinkItem : Game_Data {

		public string name = "item name";
		public string category = "item category";
		public string desc = "Item Description";
		public Type item = null;
		public int cost = 0;
		public bool last = false;
		public bool v_abstract = false;
		public ByTable gamemodes = new ByTable();
		public ByTable job = null;

		// Function from file: uplink_item.dm
		public void on_item_spawned( dynamic I = null, Mob user = null ) {
			return;
		}

		// Function from file: uplink_item.dm
		public bool buy( Ent_Static U = null, Mob user = null ) {
			dynamic I = null;
			Icon tempimage = null;
			int tempstate = 0;
			string bundlename = null;
			Mob A = null;

			Lang13.SuperCall( U, user );

			if ( !( U is Obj_Item_Device_Uplink_Hidden ) ) {
				return false;
			}

			if ( Lang13.Bool( user.stat ) || user.restrained() ) {
				return false;
			}

			if ( !( user is Mob_Living_Carbon_Human ) ) {
				return false;
			}
			Interface13.Stat( null, ((dynamic)( user.contents != null || GlobalFuncs.in_range( U.loc, user ) && U.loc.loc is Tile )).Contains( U.loc ) );

			if ( !( user is Mob_Living_Carbon_Human ) ) {
				user.set_machine( U );

				if ( this.cost > Convert.ToDouble( ((dynamic)U).uses ) ) {
					return false;
				}
				I = this.spawn_item( GlobalFuncs.get_turf( user ), U, user );

				if ( !Lang13.Bool( I ) ) {
					return false;
				}
				this.on_item_spawned( I, user );
				tempimage = new Icon( I.icon, I.icon_state );
				GlobalVars.end_icons.Add( tempimage );
				tempstate = GlobalVars.end_icons.len;
				bundlename = this.name;

				if ( this.name == "Random Item" || this.name == "For showing that you are The Boss" ) {
					bundlename = I.name;
				}

				if ( Lang13.Bool( I.tag ) ) {
					bundlename = "" + I.tag + " bundle";
					I.tag = null;
				}

				if ( user is Mob_Living_Carbon_Human ) {
					A = user;
					A.put_in_any_hand_if_possible( I );
					((dynamic)U).purchase_log += "" + user + " (" + user.ckey + ") bought <img src=\"logo_" + tempstate + ".png\"> " + this.name + " for " + this.cost + ".";
					GlobalVars.stat_collection.uplink_purchase( this, I, user );

					if ( user.mind != null ) {
						user.mind.uplink_items_bought.Add( "<img src=\"logo_" + tempstate + ".png\"> " + bundlename );
						user.mind.spent_TC += this.cost;
					}
				}
				((dynamic)U).interact( user );
				return true;
			}
			return false;
		}

		// Function from file: uplink_item.dm
		public virtual dynamic spawn_item( dynamic loc = null, Ent_Static U = null, Mob user = null ) {
			((dynamic)U).uses -= Num13.MaxInt( this.cost, 0 );
			GlobalFuncs.feedback_add_details( "traitor_uplink_items_bought", this.name );
			return Lang13.Call( this.item, loc, user );
		}

	}

}