// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Mob_Living_SimpleAnimal_Parrot_Poly_Ghost : Mob_Living_SimpleAnimal_Parrot_Poly {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.color = "#FFFFFF77";
			this.speak_chance = 20;
			this.status_flags = 4096;
			this.incorporeal_move = 1;
			this.butcher_results = new ByTable().Set( typeof(Obj_Item_Weapon_Ectoplasm), 1 );
		}

		// Function from file: parrot.dm
		public Mob_Living_SimpleAnimal_Parrot_Poly_Ghost ( dynamic loc = null ) : base( (object)(loc) ) {
			this.memory_saved = true;
			// Warning: Super call was HERE! If anything above HERE is needed by the super call, it might break!;
			return;
		}

	}

}