// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Mob_Camera_Overmind : Mob_Camera {

		public Mob_Camera_Overmind ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

		// Function from file: mind.dm
		public override void mind_initialize(  ) {
			base.mind_initialize();
			this.mind.special_role = "Blob";
			return;
		}

	}

}