// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Mob_Living_SimpleAnimal_Hostile_Construct_Harvester_Hostile : Mob_Living_SimpleAnimal_Hostile_Construct_Harvester {

		public Mob_Living_SimpleAnimal_Hostile_Construct_Harvester_Hostile ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}