// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Action_Innate_Mecha_MechToggleThrusters : Action_Innate_Mecha {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Toggle Thrusters";
			this.button_icon_state = "mech_thrusters_off";
		}

		public Action_Innate_Mecha_MechToggleThrusters ( dynamic Target = null ) : base( (object)(Target) ) {
			
		}

		// Function from file: combat.dm
		public override void Activate(  ) {
			Obj_Mecha M = null;

			
			if ( !Lang13.Bool( this.owner ) || !( this.chassis != null ) || this.chassis.occupant != this.owner ) {
				return;
			}
			M = this.chassis;

			if ( M.get_charge() > 0 ) {
				((dynamic)M).thrusters = !Lang13.Bool( ((dynamic)M).thrusters );
				this.button_icon_state = "mech_thrusters_" + ( Lang13.Bool( ((dynamic)M).thrusters ) ? "on" : "off" );
				M.log_message( "Toggled thrusters." );
				M.occupant_message( "<font color='" + ( Lang13.Bool( ((dynamic)M).thrusters ) ? "blue" : "red" ) + "'>Thrusters " + ( Lang13.Bool( ((dynamic)M).thrusters ) ? "en" : "dis" ) + "abled." );
			}
			return;
		}

	}

}