// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Barsign_Thewretchedhive : Barsign {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "The Wretched Hive";
			this.icon = "thewretchedhive";
			this.desc = "Legally obligated to instruct you to check your drinks for acid before consumption.";
		}

	}

}