// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class ChemicalReaction_Slimeoverload : ChemicalReaction {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Slime EMP";
			this.id = "m_emp";
			this.required_reagents = new ByTable().Set( "blood", 1 );
			this.result_amount = 1;
			this.required_container = typeof(Obj_Item_SlimeExtract_Yellow);
			this.required_other = true;
		}

		// Function from file: slime_extracts.dm
		public override void on_reaction( Reagents holder = null, double? created_volume = null ) {
			GlobalFuncs.feedback_add_details( "slime_cores_used", "" + this.type );
			GlobalFuncs.empulse( GlobalFuncs.get_turf( holder.my_atom ), 3, 7 );
			return;
		}

	}

}