// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Design_PowerTurbine : Design {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Machine Design (Power Turbine Board)";
			this.desc = "The circuit board for a power turbine.";
			this.id = "power_turbine";
			this.req_tech = new ByTable().Set( "programming", 4 ).Set( "powerstorage", 4 ).Set( "engineering", 5 );
			this.build_type = 1;
			this.materials = new ByTable().Set( "$glass", 1000 ).Set( "sacid", 20 );
			this.build_path = typeof(Obj_Item_Weapon_Circuitboard_PowerTurbine);
			this.category = new ByTable(new object [] { "Engineering Machinery" });
		}

	}

}