// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Disease_Transformation : Disease {

		public ByTable stage1 = new ByTable(new object [] { "You feel unremarkable." });
		public ByTable stage2 = new ByTable(new object [] { "You feel boring." });
		public ByTable stage3 = new ByTable(new object [] { "You feel utterly plain." });
		public ByTable stage4 = new ByTable(new object [] { "You feel white bread." });
		public ByTable stage5 = new ByTable(new object [] { "Oh the humanity!" });
		public Type new_form = typeof(Mob_Living_Carbon_Human);

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Transformation";
			this.max_stages = 5;
			this.spread_text = "Acute";
			this.spread_flags = 1;
			this.cure_text = "A coder's love (theoretical).";
			this.agent = "Shenanigans";
			this.viable_mobtypes = new ByTable(new object [] { typeof(Mob_Living_Carbon_Human), typeof(Mob_Living_Carbon_Monkey), typeof(Mob_Living_Carbon_Alien) });
			this.severity = "Harmful";
			this.stage_prob = 10;
			this.visibility_flags = 3;
			this.disease_flags = 1;
		}

		// Function from file: transformation.dm
		public virtual void do_disease_transformation( dynamic affected_mob = null ) {
			Obj_Item W = null;
			dynamic new_mob = null;

			
			if ( affected_mob is Mob_Living_Carbon && Convert.ToInt32( affected_mob.stat ) != 2 ) {
				
				if ( this.stage5 != null ) {
					affected_mob.WriteMsg( Rand13.PickFromTable( this.stage5 ) );
				}

				if ( GlobalFuncs.jobban_isbanned( affected_mob, this.new_form ) ) {
					((Mob)affected_mob).death( true );
					return;
				}

				if ( affected_mob.notransform == true ) {
					return;
				}
				affected_mob.notransform = true;
				affected_mob.canmove = 0;
				affected_mob.icon = null;
				affected_mob.overlays.Cut();
				affected_mob.invisibility = 101;

				foreach (dynamic _a in Lang13.Enumerate( affected_mob, typeof(Obj_Item) )) {
					W = _a;
					

					if ( W is Obj_Item_Weapon_Implant ) {
						GlobalFuncs.qdel( W );
						continue;
					}
					W.layer = Convert.ToDouble( Lang13.Initial( W, "layer" ) );
					W.loc = affected_mob.loc;
					W.dropped( affected_mob );
				}
				new_mob = Lang13.Call( this.new_form, affected_mob.loc );

				if ( new_mob is Mob_Living ) {
					new_mob.a_intent = "harm";

					if ( Lang13.Bool( affected_mob.mind ) ) {
						((Mind)affected_mob.mind).transfer_to( new_mob );
					} else {
						new_mob.key = affected_mob.key;
					}
				}
				GlobalFuncs.qdel( affected_mob );
			}
			return;
		}

		// Function from file: transformation.dm
		public override void stage_act(  ) {
			base.stage_act();

			switch ((int?)( this.stage )) {
				case 1:
					
					if ( Rand13.PercentChance( this.stage_prob ) && this.stage1 != null ) {
						this.affected_mob.WriteMsg( Rand13.PickFromTable( this.stage1 ) );
					}
					break;
				case 2:
					
					if ( Rand13.PercentChance( this.stage_prob ) && this.stage2 != null ) {
						this.affected_mob.WriteMsg( Rand13.PickFromTable( this.stage2 ) );
					}
					break;
				case 3:
					
					if ( Rand13.PercentChance( this.stage_prob * 2 ) && this.stage3 != null ) {
						this.affected_mob.WriteMsg( Rand13.PickFromTable( this.stage3 ) );
					}
					break;
				case 4:
					
					if ( Rand13.PercentChance( this.stage_prob * 2 ) && this.stage4 != null ) {
						this.affected_mob.WriteMsg( Rand13.PickFromTable( this.stage4 ) );
					}
					break;
				case 5:
					this.do_disease_transformation( this.affected_mob );
					break;
			}
			return;
		}

	}

}