// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Mob_Living_SimpleAnimal_Hostile_Creature : Mob_Living_SimpleAnimal_Hostile {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.speak_emote = new ByTable(new object [] { "screams" });
			this.icon_living = "otherthing";
			this.icon_dead = "otherthing-dead";
			this.health = 80;
			this.maxHealth = 80;
			this.melee_damage_lower = 25;
			this.melee_damage_upper = 50;
			this.attacktext = "chomps";
			this.attack_sound = "sound/weapons/bite.ogg";
			this.faction = new ByTable(new object [] { "creature" });
			this.gold_core_spawnable = 1;
			this.atmos_requirements = new ByTable().Set( "min_oxy", 0 ).Set( "max_oxy", 0 ).Set( "min_tox", 0 ).Set( "max_tox", 0 ).Set( "min_co2", 0 ).Set( "max_co2", 0 ).Set( "min_n2", 0 ).Set( "max_n2", 0 );
			this.minbodytemp = 0;
			this.icon_state = "otherthing";
		}

		public Mob_Living_SimpleAnimal_Hostile_Creature ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}