// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Mob_Living_SimpleAnimal_Hostile_Asteroid_Hivelordbrood : Mob_Living_SimpleAnimal_Hostile_Asteroid {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.icon_living = "Hivelordbrood";
			this.icon_aggro = "Hivelordbrood";
			this.icon_dead = "Hivelordbrood";
			this.icon_gib = "syndicate_gib";
			this.move_to_delay = 1;
			this.friendly = "buzzes near";
			this.vision_range = 10;
			this.speed = 3;
			this.maxHealth = 1;
			this.health = 1;
			this.harm_intent_damage = 5;
			this.melee_damage_lower = 2;
			this.melee_damage_upper = 2;
			this.attacktext = "slashes";
			this.speak_emote = new ByTable(new object [] { "telepathically cries" });
			this.attack_sound = "sound/weapons/pierce.ogg";
			this.throw_message = "falls right through the strange body of the";
			this.pass_flags = 1;
			this.del_on_death = true;
			this.icon_state = "Hivelordbrood";
		}

		// Function from file: mining_mobs.dm
		public Mob_Living_SimpleAnimal_Hostile_Asteroid_Hivelordbrood ( dynamic loc = null ) : base( (object)(loc) ) {
			// Warning: Super call was HERE! If anything above HERE is needed by the super call, it might break!;
			Task13.Schedule( 100, (Task13.Closure)(() => {
				GlobalFuncs.qdel( this );
				return;
			}));
			return;
		}

	}

}