// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_MechaParts_Part_DurandLeftArm : Obj_Item_MechaParts_Part {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.origin_tech = "programming=2;materials=3;engineering=3";
			this.icon_state = "durand_l_arm";
		}

		public Obj_Item_MechaParts_Part_DurandLeftArm ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}