// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Device_Encryptionkey_HeadsetSec : Obj_Item_Device_Encryptionkey {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.channels = new ByTable().Set( "Security", 1 );
			this.icon_state = "sec_cypherkey";
		}

		public Obj_Item_Device_Encryptionkey_HeadsetSec ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}