// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Structure_Closet_L3closet_Virology : Obj_Structure_Closet_L3closet {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.icon_state = "bio_viro";
		}

		// Function from file: l3closet.dm
		public Obj_Structure_Closet_L3closet_Virology ( dynamic loc = null ) : base( (object)(loc) ) {
			// Warning: Super call was HERE! If anything above HERE is needed by the super call, it might break!;
			this.contents = new ByTable();
			new Obj_Item_Weapon_Storage_Bag_Bio( this );
			new Obj_Item_Clothing_Suit_BioSuit_Virology( this );
			new Obj_Item_Clothing_Head_BioHood_Virology( this );
			return;
		}

	}

}