// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Weapon_ReagentContainers_Food_Snacks_Grown_Poppy_Geranium : Obj_Item_Weapon_ReagentContainers_Food_Snacks_Grown_Poppy {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.seed = typeof(Obj_Item_Seeds_Geraniumseed);
			this.filling_color = "#008B8B";
			this.icon_state = "geranium";
		}

		public Obj_Item_Weapon_ReagentContainers_Food_Snacks_Grown_Poppy_Geranium ( dynamic newloc = null, int? new_potency = null ) : base( (object)(newloc), new_potency ) {
			
		}

	}

}