// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Clothing_Mask_Gas_OwlMask : Obj_Item_Clothing_Mask_Gas {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.flags = 8;
			this.flags_cover = 2;
			this.icon_state = "owl";
		}

		public Obj_Item_Clothing_Mask_Gas_OwlMask ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}