// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_AmmoCasing_Magic_Heal : Obj_Item_AmmoCasing_Magic {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.projectile_type = typeof(Obj_Item_Projectile_Magic_Resurrection);
		}

		public Obj_Item_AmmoCasing_Magic_Heal ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}