// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Clothing_Mask_Bandana_Gold : Obj_Item_Clothing_Mask_Bandana {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.icon_state = "bandgold";
		}

		public Obj_Item_Clothing_Mask_Bandana_Gold ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}