// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Clothing_Head_Helmet_Space_Santahat : Obj_Item_Clothing_Head_Helmet_Space {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.flags = 32769;
			this.icon_state = "santahat";
		}

		public Obj_Item_Clothing_Head_Helmet_Space_Santahat ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}