// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Device_Camera_Siliconcam : Obj_Item_Device_Camera {

		public bool in_camera_mode = false;

		public Obj_Item_Device_Camera_Siliconcam ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

		// Function from file: photography.dm
		public void camera_mode_on(  ) {
			this.in_camera_mode = true;
			Task13.User.WriteMsg( "<B>Camera Mode activated</B>" );
			return;
		}

		// Function from file: photography.dm
		public void camera_mode_off(  ) {
			this.in_camera_mode = false;
			Task13.User.WriteMsg( "<B>Camera Mode deactivated</B>" );
			return;
		}

		// Function from file: photography.dm
		public void toggle_camera_mode(  ) {
			
			if ( this.in_camera_mode ) {
				this.camera_mode_off();
			} else {
				this.camera_mode_on();
			}
			return;
		}

		// Function from file: photography.dm
		public void viewpictures( dynamic user = null ) {
			Ent_Static C = null;
			Obj_Item_Device_Camera_Siliconcam Cinfo = null;
			Obj_Item_Device_Camera_Siliconcam Ainfo = null;

			
			if ( user is Mob_Living_Silicon_Robot ) {
				C = this.loc;

				if ( Lang13.Bool( ((dynamic)C).connected_ai ) ) {
					Cinfo = ((dynamic)C).connected_ai.aicamera;
					this.viewpichelper( Cinfo );
				} else {
					Cinfo = ((dynamic)C).aicamera;
					this.viewpichelper( Cinfo );
				}
			} else {
				Ainfo = this;
				this.viewpichelper( Ainfo );
			}
			return;
		}

		// Function from file: photography.dm
		public void viewpichelper( Obj_Item_Device_Camera_Siliconcam targetloc = null ) {
			Obj_Item_Weapon_Photo P = null;
			Picture selection = null;

			P = new Obj_Item_Weapon_Photo();
			selection = this.selectpicture( targetloc );

			if ( selection != null ) {
				P.photocreate( selection.fields["icon"], selection.fields["img"], selection.fields["desc"] );
				P.pixel_x = Convert.ToInt32( selection.fields["pixel_x"] );
				P.pixel_y = Convert.ToInt32( selection.fields["pixel_y"] );
				P.show( Task13.User );
				Task13.User.WriteMsg( P.desc );
			}
			GlobalFuncs.qdel( P );
			return;
		}

		// Function from file: photography.dm
		public Picture selectpicture( Obj_Item_Device_Camera_Siliconcam targetloc = null ) {
			ByTable nametemp = null;
			dynamic find = null;
			Picture t = null;
			Picture q = null;

			nametemp = new ByTable();

			if ( targetloc.aipictures.len == 0 ) {
				Task13.User.WriteMsg( "<span class='boldannounce'>No images saved</span>" );
				return null;
			}

			foreach (dynamic _a in Lang13.Enumerate( targetloc.aipictures, typeof(Picture) )) {
				t = _a;
				
				nametemp.Add( t.fields["name"] );
			}
			find = Interface13.Input( "Select image (numbered in order taken)", null, null, null, nametemp, InputType.Any );

			foreach (dynamic _b in Lang13.Enumerate( targetloc.aipictures, typeof(Picture) )) {
				q = _b;
				

				if ( q.fields["name"] == find ) {
					return q;
				}
			}
			return null;
		}

	}

}