// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Clothing_Tie_Stripedgreenscarf : Obj_Item_Clothing_Tie {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.item_color = "stripedgreenscarf";
			this.icon_state = "stripedgreenscarf";
		}

		public Obj_Item_Clothing_Tie_Stripedgreenscarf ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}