// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Weapon_Circuitboard : Obj_Item_Weapon {

		public dynamic frequency = null;
		public dynamic build_path = null;
		public string board_type = "computer";
		public ByTable req_components = null;
		public dynamic powernet = null;
		public dynamic records = null;
		public dynamic frame_desc = null;

		protected override void __FieldInit() {
			base.__FieldInit();

			this.w_class = 2;
			this.item_state = "electronic";
			this.origin_tech = "programming=2";
			this.materials = new ByTable().Set( "$glass", 200 );
			this.icon = "icons/obj/module.dmi";
			this.icon_state = "id_mod";
		}

		public Obj_Item_Weapon_Circuitboard ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}