// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Weapon_Storage_Briefcase_Lawyer : Obj_Item_Weapon_Storage_Briefcase {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.folder_path = typeof(Obj_Item_Weapon_Folder_Blue);
		}

		// Function from file: briefcase.dm
		public Obj_Item_Weapon_Storage_Briefcase_Lawyer ( dynamic loc = null ) : base( (object)(loc) ) {
			new Obj_Item_Weapon_Stamp_Law( this );
			// Warning: Super call was HERE! If anything above HERE is needed by the super call, it might break!;
			return;
		}

	}

}