// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Weapon_Circuitboard_LaborShuttle_OneWay : Obj_Item_Weapon_Circuitboard_LaborShuttle {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.build_path = typeof(Obj_Machinery_Computer_Shuttle_Labor_OneWay);
		}

		public Obj_Item_Weapon_Circuitboard_LaborShuttle_OneWay ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}