// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Structure_Sign_Kiddieplaque : Obj_Structure_Sign {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.icon_state = "kiddieplaque";
		}

		public Obj_Structure_Sign_Kiddieplaque ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}