// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Screen_Alert_Restrained_Buckled : Obj_Screen_Alert_Restrained {

		public Obj_Screen_Alert_Restrained_Buckled ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}