// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Structure_Closet_Crate_Hydroponics : Obj_Structure_Closet_Crate {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.icon_crate = "hydrocrate";
			this.icon_state = "hydrocrate";
		}

		public Obj_Structure_Closet_Crate_Hydroponics ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}