// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Clothing_Head_Collectable_Pirate : Obj_Item_Clothing_Head_Collectable {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.item_state = "pirate";
			this.icon_state = "pirate";
		}

		public Obj_Item_Clothing_Head_Collectable_Pirate ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}