// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Clothing_Head_Helmet_Space_Hardsuit_Syndi_Owl : Obj_Item_Clothing_Head_Helmet_Space_Hardsuit_Syndi {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.alt_desc = "A dual-mode advanced helmet designed for any crime-fighting situation. It is in combat mode.";
			this.item_state = "s_helmet";
			this.item_color = "owl";
			this.icon_state = "hardsuit1-owl";
		}

		public Obj_Item_Clothing_Head_Helmet_Space_Hardsuit_Syndi_Owl ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}