// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Weapon_ReagentContainers_Food_Snacks_Kebab_Tail : Obj_Item_Weapon_ReagentContainers_Food_Snacks_Kebab {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.bonus_reagents = new ByTable().Set( "nutriment", 1 ).Set( "vitamin", 4 );
		}

		public Obj_Item_Weapon_ReagentContainers_Food_Snacks_Kebab_Tail ( dynamic location = null, int? vol = null ) : base( (object)(location), vol ) {
			
		}

	}

}