// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Clothing_Head_Chefhat : Obj_Item_Clothing_Head {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.item_state = "chef";
			this.strip_delay = 10;
			this.put_on_delay = 10;
			this.icon_state = "chef";
		}

		public Obj_Item_Clothing_Head_Chefhat ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

		// Function from file: jobs.dm
		public override int suicide_act( Mob_Living_Carbon_Human user = null ) {
			user.visible_message( "<span class='suicide'>" + user + " is donning " + this + "! It looks like they're trying to become a chef.</span>" );
			user.say( "Bork Bork Bork!" );
			Task13.Sleep( 20 );
			user.visible_message( "<span class='suicide'>" + user + " climbs into an imaginary oven!</span>" );
			user.say( "BOOORK!" );
			GlobalFuncs.playsound( user, "sound/machines/ding.ogg", 50, 1 );
			return 2;
		}

	}

}