// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Effect_Swarmer_Disintegration : Obj_Effect_Swarmer {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.anchored = 1;
			this.icon_state = "disintegrate";
		}

		// Function from file: swarmer.dm
		public Obj_Effect_Swarmer_Disintegration ( dynamic loc = null ) : base( (object)(loc) ) {
			GlobalFuncs.playsound( this.loc, "sparks", 100, 1 );
			Task13.Schedule( 10, (Task13.Closure)(() => {
				GlobalFuncs.qdel( this );
				return;
			}));
			return;
		}

	}

}