// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Clothing_Suit_Armor_Riot_Knight_Templar : Obj_Item_Clothing_Suit_Armor_Riot_Knight {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.item_state = "knight_templar";
			this.icon_state = "knight_templar";
		}

		public Obj_Item_Clothing_Suit_Armor_Riot_Knight_Templar ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}