// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Structure_Closet_Critter_Chick : Obj_Structure_Closet_Critter {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.content_mob = typeof(Mob_Living_SimpleAnimal_Chick);
		}

		// Function from file: crittercrate.dm
		public Obj_Structure_Closet_Critter_Chick ( dynamic loc = null ) : base( (object)(loc) ) {
			this.amount = Rand13.Int( 1, 3 );
			// Warning: Super call was HERE! If anything above HERE is needed by the super call, it might break!;
			return;
		}

	}

}