// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Outfit_Syndicate_Full : Outfit_Syndicate {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Syndicate Operative - Full Kit";
			this.glasses = typeof(Obj_Item_Clothing_Glasses_Night);
			this.mask = typeof(Obj_Item_Clothing_Mask_Gas_Syndicate);
			this.suit = typeof(Obj_Item_Clothing_Suit_Space_Hardsuit_Syndi);
			this.l_pocket = typeof(Obj_Item_Weapon_Tank_Internals_EmergencyOxygen_Engi);
			this.r_pocket = typeof(Obj_Item_Weapon_Gun_Projectile_Automatic_Pistol);
			this.belt = typeof(Obj_Item_Weapon_Storage_Belt_Military);
			this.r_hand = typeof(Obj_Item_Weapon_Gun_Projectile_Automatic_Shotgun_Bulldog);
			this.backpack_contents = new ByTable().Set( typeof(Obj_Item_Weapon_Storage_Box_Engineer), 1 ).Set( typeof(Obj_Item_Weapon_Tank_Jetpack_Oxygen_Harness), 1 ).Set( typeof(Obj_Item_Weapon_Pinpointer_Nukeop), 1 );
		}

		// Function from file: nuclear.dm
		public override void post_equip( Mob H = null, bool? visualsOnly = null ) {
			Obj_Item_Clothing_Suit_Space_Hardsuit suit = null;
			Obj_Item helmet = null;

			base.post_equip( H, visualsOnly );
			suit = ((dynamic)H).wear_suit;
			suit.ToggleHelmet();
			helmet = ((dynamic)H).head;
			helmet.attack_self( H );
			((dynamic)H).v_internal = ((dynamic)H).l_store;
			return;
		}

	}

}