// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Outfit_Job_Hos : Outfit_Job {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Head of Security";
			this.id = typeof(Obj_Item_Weapon_Card_Id_Silver);
			this.belt = typeof(Obj_Item_Device_Pda_Heads_Hos);
			this.ears = typeof(Obj_Item_Device_Radio_Headset_Heads_Hos_Alt);
			this.uniform = typeof(Obj_Item_Clothing_Under_Rank_HeadOfSecurity);
			this.shoes = typeof(Obj_Item_Clothing_Shoes_Jackboots);
			this.suit = typeof(Obj_Item_Clothing_Suit_Armor_Hos_Trenchcoat);
			this.gloves = typeof(Obj_Item_Clothing_Gloves_Color_Black_Hos);
			this.head = typeof(Obj_Item_Clothing_Head_HoS_Beret);
			this.glasses = typeof(Obj_Item_Clothing_Glasses_Hud_Security_Sunglasses);
			this.suit_store = typeof(Obj_Item_Weapon_Gun_Energy_Gun);
			this.backpack_contents = new ByTable().Set( typeof(Obj_Item_Weapon_Melee_ClassicBaton_Telescopic), 1 ).Set( typeof(Obj_Item_Weapon_Restraints_Handcuffs), 1 );
			this.backpack = typeof(Obj_Item_Weapon_Storage_Backpack_Security);
			this.satchel = typeof(Obj_Item_Weapon_Storage_Backpack_SatchelSec);
		}

		// Function from file: security.dm
		public override void post_equip( Mob H = null, bool? visualsOnly = null ) {
			visualsOnly = visualsOnly ?? GlobalVars.FALSE;

			Obj_Item_Weapon_Implant_Loyalty L = null;

			base.post_equip( H, visualsOnly );

			if ( visualsOnly == true ) {
				return;
			}
			L = new Obj_Item_Weapon_Implant_Loyalty( H );
			L.imp_in = H;
			L.implanted = 1;
			((Mob_Living_Carbon_Human)H).sec_hud_set_implants();
			this.announce_head( H, new ByTable(new object [] { "Security" }) );
			return;
		}

	}

}