// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Reagent_Consumable_DrGibb : Reagent_Consumable {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Dr. Gibb";
			this.id = "dr_gibb";
			this.description = "A delicious blend of 42 different flavours";
			this.color = "#102000";
		}

		// Function from file: drink_reagents.dm
		public override bool on_mob_life( dynamic M = null ) {
			M.drowsyness = Num13.MaxInt( 0, M.drowsyness - 6 );

			if ( Convert.ToDouble( M.bodytemperature ) > 310 ) {
				M.bodytemperature = Num13.MaxInt( 310, Convert.ToInt32( M.bodytemperature - 7.5 ) );
			}
			base.on_mob_life( (object)(M) );
			return false;
		}

	}

}