// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Reagent_Toxin_Beer2 : Reagent_Toxin {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Beer";
			this.id = "beer2";
			this.description = "A specially-engineered sedative disguised as beer. It induces instant sleep in its target.";
			this.color = "#664300";
			this.metabolization_rate = 0.6;
		}

		// Function from file: toxin_reagents.dm
		public override bool on_mob_life( dynamic M = null ) {
			
			dynamic _a = this.current_cycle; // Was a switch-case, sorry for the mess.
			if ( 1<=_a&&_a<=50 ) {
				M.sleeping += 1;
			} else if ( 51<=_a&&_a<=Double.PositiveInfinity ) {
				M.sleeping += 1;
				((Mob_Living)M).adjustToxLoss( this.current_cycle - 50 );
			}
			base.on_mob_life( (object)(M) );
			return false;
		}

	}

}