// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class SpriteAccessory_FacialHair_Longbeard : SpriteAccessory_FacialHair {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Long Beard";
			this.icon_state = "facial_longbeard";
		}

	}

}