// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class SupplyPacks_Emergency_Atmostank : SupplyPacks_Emergency {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Firefighting Watertank";
			this.contains = new ByTable(new object [] { typeof(Obj_Item_Weapon_Watertank_Atmos) });
			this.cost = 10;
			this.containertype = typeof(Obj_Structure_Closet_Crate_Secure);
			this.containername = "firefighting watertank crate";
			this.access = 24;
		}

	}

}