// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class SupplyPacks_Organic_Pizza : SupplyPacks_Organic {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Pizza Crate";
			this.contains = new ByTable(new object [] { typeof(Obj_Item_Pizzabox_Margherita), typeof(Obj_Item_Pizzabox_Mushroom), typeof(Obj_Item_Pizzabox_Meat), typeof(Obj_Item_Pizzabox_Vegetable) });
			this.cost = 60;
			this.containername = "Pizza crate";
		}

	}

}