// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Surgery_CoreRemoval : Surgery {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "core removal";
			this.steps = new ByTable(new object [] { typeof(SurgeryStep_Incise), typeof(SurgeryStep_Incise), typeof(SurgeryStep_ExtractCore) });
			this.species = new ByTable(new object [] { typeof(Mob_Living_SimpleAnimal_Slime) });
		}

		// Function from file: core_removal.dm
		public override bool can_start( dynamic user = null, dynamic target = null ) {
			
			if ( Convert.ToInt32( target.stat ) == 2 ) {
				return true;
			}
			return false;
		}

	}

}