// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Symptom_Stimulant : Symptom {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Stimulant";
			this.stealth = -1;
			this.resistance = -3;
			this.stage_speed = -2;
			this.transmittable = -4;
			this.level = 3;
		}

		// Function from file: tgstation.dme
		public override void Activate( Disease_Advance A = null ) {
			dynamic M = null;

			base.Activate( A );

			if ( Rand13.PercentChance( 30 ) ) {
				M = A.affected_mob;

				switch ((int?)( A.stage )) {
					case 5:
						
						if ( ( ((Reagents)M.reagents).get_reagent_amount( "ephedrine" ) ?1:0) < 10 ) {
							((Reagents)M.reagents).add_reagent( "ephedrine", 10 );
						}
						break;
					default:
						
						if ( Rand13.PercentChance( 15 ) ) {
							M.WriteMsg( "<span class='notice'>" + Rand13.Pick(new object [] { "You feel restless.", "You feel like running laps around the station." }) + "</span>" );
						}
						break;
				}
			}
			return;
		}

	}

}