// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Tile_Simulated_Floor_Holofloor_Beach_Coast : Tile_Simulated_Floor_Holofloor_Beach {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.icon = "icons/misc/beach2.dmi";
			this.icon_state = "sandwater";
		}

		public Tile_Simulated_Floor_Holofloor_Beach_Coast ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}