// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class UplinkItem_Specoffer_Sniper : UplinkItem_Specoffer {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.name = "Sniper bundle";
			this.desc = "Contains a collapsed sniper rifle in an expensive carrying case, a hollowpoint haemorrhage magazine, a soporific knockout magazine, a free surplus supressor, and a worn out suit and tie.";
			this.item = typeof(Obj_Item_Weapon_Storage_Briefcase_Sniperbundle);
			this.cost = 20;
			this.gamemodes = new ByTable(new object [] { typeof(GameMode_Nuclear) });
		}

	}

}