// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Zone_Derelict_Hallway_Primary : Zone_Derelict_Hallway {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.icon_state = "hallP";
		}

		public Zone_Derelict_Hallway_Primary ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}