// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Zone_Security : Zone {

		public Zone_Security ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}