// FILE AUTOGENERATED BY SOM13. DO NOT EDIT YET.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Zone_Mine_Sleeper : Zone_Mine {

		public Zone_Mine_Sleeper ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}