// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Device_Radio_Headset_Syndicate_Alt_Leader : Obj_Item_Device_Radio_Headset_Syndicate_Alt {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.command = 1;
		}

		public Obj_Item_Device_Radio_Headset_Syndicate_Alt_Leader ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}