// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Structure_Window_Reinforced_Tinted : Obj_Structure_Window_Reinforced {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.sheettype = typeof(Obj_Item_Stack_Sheet_Glass_Rglass);
			this.icon_state = "twindow";
		}

		public Obj_Structure_Window_Reinforced_Tinted ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}