// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Clothing_Under_Shorts_Black : Obj_Item_Clothing_Under_Shorts {

		protected override void __FieldInit() {
			base.__FieldInit();

			this._color = "blackshorts";
			this.icon_state = "blackshorts";
		}

		public Obj_Item_Clothing_Under_Shorts_Black ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}