// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Projectile_Forcebolt_Strong : Obj_Item_Projectile_Forcebolt {

		public Obj_Item_Projectile_Forcebolt_Strong ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

		// Function from file: force.dm
		public override bool on_hit( dynamic atarget = null, int? blocked = null ) {
			blocked = blocked ?? 0;

			int? throwdir = null;
			dynamic M = null;
			dynamic MM = null;

			this.damage = 30;
			throwdir = null;

			foreach (dynamic _a in Lang13.Enumerate( Map13.FetchHearers( this, 1 ) )) {
				M = _a;
				

				if ( M == this.firer ) {
					continue;
				}

				if ( M.loc != this.loc ) {
					throwdir = Map13.GetDistance( this, atarget );

					if ( Rand13.PercentChance( 75 ) ) {
						
						if ( M is Mob_Living_Carbon ) {
							MM = M;
							((Mob_Living)MM).apply_effect( 2, "weaken" );
							GlobalFuncs.to_chat( MM, "<span class='warning'>The force knocks you off your feet!</span>" );
						}
					}
					((Ent_Dynamic)M).throw_at( GlobalFuncs.get_edge_target_turf( M, throwdir ), 15, 1 );
				}
			}
			return base.on_hit( (object)(atarget), blocked );
		}

	}

}