// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Effect_Decal_Cleanable_Vomit : Obj_Effect_Decal_Cleanable {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.anchored = 1;
			this.basecolor = "#FFFF99";
			this.amount = 2;
			this.random_icon_states = new ByTable(new object [] { "vomit_1", "vomit_2", "vomit_3", "vomit_4" });
			this.transfers_dna = true;
			this.icon = "icons/effects/blood.dmi";
			this.icon_state = "vomit_1";
		}

		public Obj_Effect_Decal_Cleanable_Vomit ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}