// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Stack_Sheet_Hairlesshide : Obj_Item_Stack_Sheet {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.singular_name = "hairless hide piece";
			this.origin_tech = "";
			this.icon = "icons/obj/butchering_products.dmi";
			this.icon_state = "sheet-hairlesshide";
		}

		public Obj_Item_Stack_Sheet_Hairlesshide ( dynamic newloc = null, int? amount = null ) : base( (object)(newloc), amount ) {
			
		}

	}

}