// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Weapon_Circuitboard_Mecha_Ripley_Main : Obj_Item_Weapon_Circuitboard_Mecha_Ripley {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.icon_state = "mainboard";
		}

		public Obj_Item_Weapon_Circuitboard_Mecha_Ripley_Main ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}