// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Machinery_RND_Server_Core : Obj_Machinery_RND_Server {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.id_with_upload_string = "1";
			this.id_with_download_string = "1";
			this.server_id = 1;
		}

		public Obj_Machinery_RND_Server_Core ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}