// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Weapon_Stool_Hologram : Obj_Item_Weapon_Stool {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.sheet_path = null;
		}

		public Obj_Item_Weapon_Stool_Hologram ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}