// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Machinery_Bioprinter_Prosthetics : Obj_Machinery_Bioprinter {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.prints_prosthetics = true;
		}

		public Obj_Machinery_Bioprinter_Prosthetics ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}