// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Device_Powersink : Obj_Item_Device {

		public int drain_rate = 600000;
		public double power_drained = 0;
		public double max_power = 100000000;
		public int mode = 0;
		public dynamic attached = null;

		protected override void __FieldInit() {
			base.__FieldInit();

			this.item_state = "electronic";
			this.w_class = 4;
			this.throwforce = 5;
			this.throw_speed = 1;
			this.throw_range = 2;
			this.starting_materials = new ByTable().Set( "$iron", 750 );
			this.w_type = 5;
			this.melt_temperature = 1783.1500244140625;
			this.origin_tech = "powerstorage=3;syndicate=5";
			this.icon_state = "powersink0";
		}

		public Obj_Item_Device_Powersink ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

		// Function from file: powersink.dm
		public override dynamic process(  ) {
			dynamic PN = null;
			int drained = 0;
			Obj_Machinery_Power_Terminal T = null;
			Ent_Static A = null;

			
			if ( Lang13.Bool( this.attached ) ) {
				PN = this.attached.get_powernet();

				if ( Lang13.Bool( PN ) ) {
					this.set_light( 12 );
					drained = Num13.MinInt( this.drain_rate, ((int)( PN.avail )) );
					PN.load += drained;
					this.power_drained += drained;

					if ( drained < this.drain_rate ) {
						
						foreach (dynamic _a in Lang13.Enumerate( PN.nodes, typeof(Obj_Machinery_Power_Terminal) )) {
							T = _a;
							

							if ( T.master is Obj_Machinery_Power_Apc ) {
								A = T.master;

								if ( Lang13.Bool( ((dynamic)A).operating ) && Lang13.Bool( ((dynamic)A).cell ) ) {
									((dynamic)A).cell.charge = Num13.MaxInt( 0, Convert.ToInt32( ((dynamic)A).cell.charge - 50 ) );
									this.power_drained += 50;

									if ( Convert.ToInt32( ((dynamic)A).charging ) == 2 ) {
										((dynamic)A).charging = 1;
									}
								}
							}
						}
					}
				}

				if ( this.power_drained > this.max_power * 0.41 ) {
					GlobalFuncs.playsound( this, "sound/effects/screech.ogg", 100, 1, 1 );
				}

				if ( this.power_drained >= this.max_power ) {
					GlobalVars.processing_objects.Remove( this );
					GlobalFuncs.explosion( this.loc, 3, 6, 9, 12 );
					GlobalFuncs.qdel( this );
				}
			}
			return null;
		}

		// Function from file: powersink.dm
		public override dynamic attack_hand( dynamic a = null, dynamic b = null, dynamic c = null ) {
			dynamic M = null;
			dynamic M2 = null;

			
			switch ((int)( this.mode )) {
				case 0:
					base.attack_hand( (object)(a), (object)(b), (object)(c) );
					break;
				case 1:
					GlobalFuncs.to_chat( a, "You activate the device!" );

					foreach (dynamic _a in Lang13.Enumerate( Map13.FetchViewers( null, a ) )) {
						M = _a;
						

						if ( M == a ) {
							continue;
						}
						GlobalFuncs.to_chat( M, "" + a + " activates the power sink!" );
					}
					this.mode = 2;
					this.icon_state = "powersink1";
					GlobalFuncs.playsound( GlobalFuncs.get_turf( this ), "sound/effects/phasein.ogg", 30, 1 );
					GlobalVars.processing_objects.Add( this );
					break;
				case 2:
					GlobalFuncs.to_chat( a, "You deactivate the device!" );

					foreach (dynamic _b in Lang13.Enumerate( Map13.FetchViewers( null, a ) )) {
						M2 = _b;
						

						if ( M2 == a ) {
							continue;
						}
						GlobalFuncs.to_chat( M2, "" + a + " deactivates the power sink!" );
					}
					this.mode = 1;
					this.set_light( 0 );
					this.icon_state = "powersink0";
					GlobalFuncs.playsound( GlobalFuncs.get_turf( this ), "sound/effects/teleport.ogg", 50, 1 );
					GlobalVars.processing_objects.Remove( this );
					break;
			}
			return null;
		}

		// Function from file: powersink.dm
		public override dynamic attack_ai( dynamic user = null ) {
			return null;
		}

		// Function from file: powersink.dm
		public override dynamic attack_paw( Mob a = null, dynamic b = null, dynamic c = null ) {
			return null;
		}

		// Function from file: powersink.dm
		public override dynamic Destroy( dynamic brokenup = null ) {
			this.set_light( 0 );
			GlobalVars.processing_objects.Remove( this );
			this.attached.attached = null;
			this.attached = null;
			base.Destroy( (object)(brokenup) );
			return null;
		}

		// Function from file: powersink.dm
		public override dynamic attackby( dynamic a = null, dynamic b = null, dynamic c = null ) {
			Ent_Static T = null;
			dynamic M = null;
			dynamic M2 = null;

			
			if ( a is Obj_Item_Weapon_Screwdriver ) {
				
				if ( this.mode == 0 ) {
					T = this.loc;

					if ( T is Tile && !Lang13.Bool( ((dynamic)T).intact ) ) {
						this.attached = Lang13.FindIn( typeof(Obj_Structure_Cable), T );

						if ( !Lang13.Bool( this.attached ) ) {
							GlobalFuncs.to_chat( b, "No exposed cable here to attach to." );
							return null;
						} else {
							this.attached.attached = this;
							this.anchored = 1;
							this.mode = 1;
							GlobalFuncs.to_chat( b, "You attach the device to the cable." );

							foreach (dynamic _a in Lang13.Enumerate( Map13.FetchViewers( null, b ) )) {
								M = _a;
								

								if ( M == b ) {
									continue;
								}
								GlobalFuncs.to_chat( M, "" + b + " attaches the power sink to the cable." );
							}
							return null;
						}
					} else {
						GlobalFuncs.to_chat( b, "Device must be placed over an exposed cable to attach to it." );
						return null;
					}
				} else {
					
					if ( this.mode == 2 ) {
						GlobalVars.processing_objects.Remove( this );
					}
					this.anchored = 0;
					this.mode = 0;
					GlobalFuncs.to_chat( b, "You detach the device from the cable." );
					this.attached.attached = null;
					this.attached = null;

					foreach (dynamic _b in Lang13.Enumerate( Map13.FetchViewers( null, b ) )) {
						M2 = _b;
						

						if ( M2 == b ) {
							continue;
						}
						GlobalFuncs.to_chat( M2, "" + b + " detaches the power sink from the cable." );
					}
					this.set_light( 0 );
					this.icon_state = "powersink0";
					return null;
				}
			} else {
				base.attackby( (object)(a), (object)(b), (object)(c) );
			}
			return null;
		}

	}

}