// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Structure_DeathsquadTele : Obj_Structure {

		public bool ztarget = false;
		public string id_tag = "";

		protected override void __FieldInit() {
			base.__FieldInit();

			this.anchored = 1;
			this.icon = "icons/obj/stationobjs.dmi";
			this.icon_state = "tele0";
		}

		public Obj_Structure_DeathsquadTele ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

		// Function from file: pod.dm
		public override bool Bumped( Ent_Static AM = null, dynamic yes = null ) {
			int y = 0;
			dynamic target = null;

			
			if ( !this.ztarget ) {
				return base.Bumped( AM, (object)(yes) );
			}
			y = AM.y;
			Task13.Schedule( 0, (Task13.Closure)(() => {
				AM.z = this.ztarget ?1:0;
				AM.y = y;
				AM.x = Game13.map_size_x - 7 - 2;
				AM.dir = 8;
				target = GlobalFuncs.get_edge_target_turf( AM, AM.dir );
				((Ent_Dynamic)AM).throw_at( target, 50, ((dynamic)AM).throw_speed );
				return;
			}));
			return false;
		}

	}

}