// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Clothing_Under_Overalls : Obj_Item_Clothing_Under {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.item_state = "lb_suit";
			this.item_color = "overalls";
			this.can_adjust = false;
			this.icon_state = "overalls";
		}

		public Obj_Item_Clothing_Under_Overalls ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}