// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Clothing_Glasses_Regular : Obj_Item_Clothing_Glasses {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.item_state = "glasses";
			this.prescription = true;
			this.icon_state = "glasses";
		}

		public Obj_Item_Clothing_Glasses_Regular ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}