// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Structure_Bed_Chair_Comfy : Obj_Structure_Bed_Chair {

		public Image armrest = null;

		protected override void __FieldInit() {
			base.__FieldInit();

			this.icon_state = "comfychair_black";
		}

		// Function from file: chairs.dm
		public Obj_Structure_Bed_Chair_Comfy ( dynamic loc = null ) : base( (object)(loc) ) {
			// Warning: Super call was HERE! If anything above HERE is needed by the super call, it might break!;
			this.armrest = new Image( "icons/obj/objects.dmi", "" + this.icon_state + "_armrest", 401 );
			return;
		}

		// Function from file: chairs.dm
		public override bool? update_icon( dynamic location = null, dynamic target = null ) {
			base.update_icon( (object)(location), (object)(target) );

			if ( this.locked_atoms.len != 0 ) {
				this.overlays.Add( this.armrest );
			} else {
				this.overlays.Remove( this.armrest );
			}
			return null;
		}

		// Function from file: chairs.dm
		public override bool unlock_atom( dynamic AM = null ) {
			base.unlock_atom( (object)(AM) );
			this.update_icon();
			return false;
		}

		// Function from file: chairs.dm
		public override bool lock_atom( dynamic AM = null ) {
			base.lock_atom( (object)(AM) );
			this.update_icon();
			return false;
		}

	}

}