// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Clothing_Gloves_Color : Obj_Item_Clothing_Gloves {

		public Obj_Item_Clothing_Gloves_Color ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}