// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Borg_Sight_Xray : Obj_Item_Borg_Sight {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.sight_mode = 4;
			this.icon = "icons/obj/decals.dmi";
			this.icon_state = "securearea";
		}

		public Obj_Item_Borg_Sight_Xray ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}