// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Structure_AIcore : Obj_Structure {

		public int state = 0;
		public dynamic laws = null;
		public dynamic circuit = null;
		public dynamic brain = null;

		protected override void __FieldInit() {
			base.__FieldInit();

			this.icon = "icons/mob/AI.dmi";
			this.icon_state = "0";
		}

		// Function from file: ai_core.dm
		public Obj_Structure_AIcore ( dynamic loc = null ) : base( (object)(loc) ) {
			// Warning: Super call was HERE! If anything above HERE is needed by the super call, it might break!;
			this.laws = Lang13.Call( GlobalVars.base_law_type );
			return;
		}

		// Function from file: ai_core.dm
		public override dynamic attackby( dynamic a = null, dynamic b = null, dynamic c = null ) {
			dynamic WT = null;
			Obj_Item_Stack_CableCoil A = null;
			Mob_Living_Silicon_Ai A2 = null;

			
			switch ((int)( this.state )) {
				case 0:
					
					if ( a is Obj_Item_Weapon_Wrench ) {
						GlobalFuncs.playsound( this.loc, "sound/items/Ratchet.ogg", 50, 1 );

						if ( GlobalFuncs.do_after( b, this, 20 ) ) {
							GlobalFuncs.to_chat( b, "<span class='notice'>You wrench the frame into place.</span>" );
							this.anchored = 1;
							this.state = 1;
						}
					}

					if ( a is Obj_Item_Weapon_Weldingtool ) {
						WT = a;

						if ( !((Obj_Item_Weapon_Weldingtool)WT).isOn() ) {
							GlobalFuncs.to_chat( b, "The welder must be on for this task." );
							return null;
						}
						GlobalFuncs.playsound( this.loc, "sound/items/welder.ogg", 50, 1 );

						if ( GlobalFuncs.do_after( b, this, 20 ) ) {
							
							if ( !( this != null ) || !Lang13.Bool( WT.remove_fuel( 0, b ) ) ) {
								return null;
							}
							GlobalFuncs.to_chat( b, "<span class='notice'>You deconstruct the frame.</span>" );
							new Obj_Item_Stack_Sheet_Plasteel( this.loc, 4 );
							GlobalFuncs.qdel( this );
						}
					}
					break;
				case 1:
					
					if ( a is Obj_Item_Weapon_Wrench ) {
						GlobalFuncs.playsound( this.loc, "sound/items/Ratchet.ogg", 50, 1 );

						if ( GlobalFuncs.do_after( b, this, 20 ) ) {
							GlobalFuncs.to_chat( b, "<span class='notice'>You unfasten the frame.</span>" );
							this.anchored = 0;
							this.state = 0;
						}
					}

					if ( a is Obj_Item_Weapon_Circuitboard_Aicore && !Lang13.Bool( this.circuit ) ) {
						
						if ( Lang13.Bool( b.drop_item( a, this ) ) ) {
							GlobalFuncs.playsound( this.loc, "sound/items/Deconstruct.ogg", 50, 1 );
							GlobalFuncs.to_chat( b, "<span class='notice'>You place the circuit board inside the frame.</span>" );
							this.icon_state = "1";
							this.circuit = a;
						}
					}

					if ( a is Obj_Item_Weapon_Screwdriver && Lang13.Bool( this.circuit ) ) {
						GlobalFuncs.playsound( this.loc, "sound/items/Screwdriver.ogg", 50, 1 );
						GlobalFuncs.to_chat( b, "<span class='notice'>You screw the circuit board into place.</span>" );
						this.state = 2;
						this.icon_state = "2";
					}

					if ( a is Obj_Item_Weapon_Crowbar && Lang13.Bool( this.circuit ) ) {
						GlobalFuncs.playsound( this.loc, "sound/items/Crowbar.ogg", 50, 1 );
						GlobalFuncs.to_chat( b, "<span class='notice'>You remove the circuit board.</span>" );
						this.state = 1;
						this.icon_state = "0";
						this.circuit.loc = this.loc;
						this.circuit = null;
					}
					break;
				case 2:
					
					if ( a is Obj_Item_Weapon_Screwdriver && Lang13.Bool( this.circuit ) ) {
						GlobalFuncs.playsound( this.loc, "sound/items/Screwdriver.ogg", 50, 1 );
						GlobalFuncs.to_chat( b, "<span class='notice'>You unfasten the circuit board.</span>" );
						this.state = 1;
						this.icon_state = "1";
					}

					if ( a is Obj_Item_Stack_CableCoil ) {
						
						if ( Convert.ToDouble( a.amount ) >= 5 ) {
							GlobalFuncs.playsound( this.loc, "sound/items/Deconstruct.ogg", 50, 1 );

							if ( GlobalFuncs.do_after( b, this, 20 ) ) {
								a.amount -= 5;

								if ( !Lang13.Bool( a.amount ) ) {
									GlobalFuncs.qdel( a );
								}

								if ( !Lang13.Bool( a.amount ) ) {
									GlobalFuncs.qdel( a );
								}
								GlobalFuncs.to_chat( b, "<span class='notice'>You add cables to the frame.</span>" );
								this.state = 3;
								this.icon_state = "3";
							}
						}
					}
					break;
				case 3:
					
					if ( a is Obj_Item_Weapon_Wirecutters ) {
						
						if ( Lang13.Bool( this.brain ) ) {
							GlobalFuncs.to_chat( b, "Get that brain out of there first" );
						} else {
							GlobalFuncs.playsound( this.loc, "sound/items/Wirecutter.ogg", 50, 1 );
							GlobalFuncs.to_chat( b, "<span class='notice'>You remove the cables.</span>" );
							this.state = 2;
							this.icon_state = "2";
							A = new Obj_Item_Stack_CableCoil( this.loc );
							A.amount = 5;
						}
					}

					if ( a is Obj_Item_Stack_Sheet_Glass_Rglass ) {
						
						if ( Convert.ToDouble( a.amount ) >= 2 ) {
							GlobalFuncs.playsound( this.loc, "sound/items/Deconstruct.ogg", 50, 1 );

							if ( GlobalFuncs.do_after( b, this, 20 ) ) {
								
								if ( Lang13.Bool( a ) ) {
									a.amount -= 2;

									if ( !Lang13.Bool( a.amount ) ) {
										GlobalFuncs.qdel( a );
									}

									if ( !Lang13.Bool( a.amount ) ) {
										GlobalFuncs.qdel( a );
									}
									GlobalFuncs.to_chat( b, "<span class='notice'>You put in the glass panel.</span>" );
									this.state = 4;
									this.icon_state = "4";
								}
							}
						}
					}

					if ( a is Obj_Item_Device_Mmi ) {
						
						if ( !Lang13.Bool( a.brainmob ) ) {
							GlobalFuncs.to_chat( b, "<span class='warning'>Sticking an empty " + a + " into the frame would sort of defeat the purpose.</span>" );
							return null;
						}

						if ( Convert.ToInt32( a.brainmob.stat ) == 2 ) {
							GlobalFuncs.to_chat( b, "<span class='warning'>Sticking a dead " + a + " into the frame would sort of defeat the purpose.</span>" );
							return null;
						}

						if ( Lang13.Bool( GlobalFuncs.jobban_isbanned( a.brainmob, "AI" ) ) ) {
							GlobalFuncs.to_chat( b, "<span class='warning'>This " + a + " does not seem to fit.</span>" );
							return null;
						}

						if ( !Lang13.Bool( b.drop_item( a, this ) ) ) {
							b.WriteMsg( new Txt( "<span class='warning'>You can't let go of " ).the( a ).item().str( "!</span>" ).ToString() );
							return null;
						}

						if ( Lang13.Bool( a.brainmob.mind ) ) {
							((GameMode)GlobalVars.ticker.mode).remove_cultist( a.brainmob.mind, true );
							((GameMode)GlobalVars.ticker.mode).remove_revolutionary( a.brainmob.mind, true );
						}

						if ( !Lang13.Bool( this.brain ) ) {
							
							if ( Lang13.Bool( b.drop_item( a, this ) ) ) {
								this.brain = a;
								GlobalFuncs.to_chat( b, "Added " + a + "." );
								this.icon_state = "3b";
							}
						}
					}

					if ( a is Obj_Item_Weapon_Crowbar && Lang13.Bool( this.brain ) ) {
						GlobalFuncs.playsound( this.loc, "sound/items/Crowbar.ogg", 50, 1 );
						GlobalFuncs.to_chat( b, "<span class='notice'>You remove the brain.</span>" );
						this.brain.loc = this.loc;
						this.brain = null;
						this.icon_state = "3";
					}
					break;
				case 4:
					
					if ( a is Obj_Item_Weapon_Crowbar ) {
						GlobalFuncs.playsound( this.loc, "sound/items/Crowbar.ogg", 50, 1 );
						GlobalFuncs.to_chat( b, "<span class='notice'>You remove the glass panel.</span>" );
						this.state = 3;

						if ( Lang13.Bool( this.brain ) ) {
							this.icon_state = "3b";
						} else {
							this.icon_state = "3";
						}
						new Obj_Item_Stack_Sheet_Glass_Rglass( this.loc, 2 );
						return null;
					}

					if ( a is Obj_Item_Weapon_Screwdriver ) {
						GlobalFuncs.playsound( this.loc, "sound/items/Screwdriver.ogg", 50, 1 );
						GlobalFuncs.to_chat( b, "<span class='notice'>You connect the monitor.</span>" );
						A2 = new Mob_Living_Silicon_Ai( this.loc, this.laws, this.brain );

						if ( A2 != null ) {
							A2.rename_self( "ai", true );
						}
						GlobalFuncs.feedback_inc( "cyborg_ais_created", 1 );
						GlobalFuncs.qdel( this );
					}
					break;
			}
			return null;
		}

	}

}