// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Clothing_Suit_Cardborg : Obj_Item_Clothing_Suit {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.item_state = "cardborg";
			this.starting_materials = new ByTable().Set( "$cardboard", 11250 );
			this.w_type = 1;
			this.icon_state = "cardborg";
		}

		public Obj_Item_Clothing_Suit_Cardborg ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}