// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Effect_Overlay_Temp_Swarmer_Integrate : Obj_Effect_Overlay_Temp_Swarmer {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.duration = 5;
			this.icon_state = "integrate";
		}

		public Obj_Effect_Overlay_Temp_Swarmer_Integrate ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}