// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Clothing_Suit_Cloak_Rd : Obj_Item_Clothing_Suit_Cloak {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.armor = new ByTable().Set( "melee", 0 ).Set( "bullet", 0 ).Set( "laser", 0 ).Set( "energy", 0 ).Set( "bomb", 10 ).Set( "bio", 10 ).Set( "rad", 0 );
			this.icon_state = "rdcloak";
		}

		public Obj_Item_Clothing_Suit_Cloak_Rd ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}