// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Machinery_Hologram_Projector : Obj_Machinery_Hologram {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.icon_state = "hologram0";
		}

		public Obj_Machinery_Hologram_Projector ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}