// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Effect_ProcHolder_Spell_Self_ShadowlingHivemindAscendant : Obj_Effect_ProcHolder_Spell_Self {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.panel = "Ascendant";
			this.charge_max = 0;
			this.clothes_req = 0;
			this.action_icon_state = "commune";
		}

		public Obj_Effect_ProcHolder_Spell_Self_ShadowlingHivemindAscendant ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

		// Function from file: shadowling_abilities.dm
		public override bool cast( dynamic targets = null, dynamic thearea = null, dynamic user = null ) {
			string text = null;
			dynamic M = null;

			text = GlobalFuncs.stripped_input( targets, "What do you want to say to fellow thralls and shadowlings?.", "Hive Chat", "" );

			if ( !Lang13.Bool( text ) ) {
				return false;
			}
			text = "<font size=4><span class='shadowling'><b>[Ascendant]<i> " + targets.real_name + "</i>: " + text + "</b></span></font>";

			foreach (dynamic _a in Lang13.Enumerate( GlobalVars.mob_list )) {
				M = _a;
				

				if ( GlobalFuncs.is_shadow_or_thrall( M ) ) {
					M.WriteMsg( text );
				}

				if ( M is Mob_Dead_Observer ) {
					M.WriteMsg( new Txt( "<a href='?src=" ).Ref( M ).str( ";follow=" ).Ref( targets ).str( "'>(F)</a> " ).item( text ).ToString() );
				}
			}
			GlobalFuncs.log_say( "" + targets.real_name + "/" + targets.key + " : " + text );
			return false;
		}

	}

}