// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Weapon_Weldingtool_Experimental_Empty : Obj_Item_Weapon_Weldingtool_Experimental {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.start_fueled = false;
		}

		public Obj_Item_Weapon_Weldingtool_Experimental_Empty ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}