// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Effect_Decal_Cleanable_RobotDebris_Gib : Obj_Effect_Decal_Cleanable_RobotDebris {

		public Obj_Effect_Decal_Cleanable_RobotDebris_Gib ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

		// Function from file: disposal-structures.dm
		public override void pipe_eject( int? direction = null ) {
			ByTable dirs = null;

			
			if ( Lang13.Bool( direction ) ) {
				dirs = new ByTable(new object [] { direction, Num13.Rotate( direction, -45 ), Num13.Rotate( direction, 45 ) });
			} else {
				dirs = GlobalVars.alldirs.Copy();
			}
			this.streak( dirs );
			return;
		}

	}

}