// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Device_Flashlight_Lamp_Green : Obj_Item_Device_Flashlight_Lamp {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.item_state = "lampgreen";
			this.icon_state = "lampgreen";
		}

		public Obj_Item_Device_Flashlight_Lamp_Green ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}