// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Clothing_Glasses_Sunglasses : Obj_Item_Clothing_Glasses {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.item_state = "sunglasses";
			this.origin_tech = "combat=2";
			this.darkness_view = -1;
			this.eyeprot = 1;
			this.species_fit = new ByTable(new object [] { "Vox" });
			this.icon_state = "sun";
		}

		public Obj_Item_Clothing_Glasses_Sunglasses ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}