// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Effect_ProcHolder_Spell_Targeted_InflictHandler_Blind : Obj_Effect_ProcHolder_Spell_Targeted_InflictHandler {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.amt_eye_blind = 10;
			this.amt_eye_blurry = 20;
			this.sound = "sound/magic/Blind.ogg";
		}

		public Obj_Effect_ProcHolder_Spell_Targeted_InflictHandler_Blind ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}