// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Weapon_ReagentContainers_Food_Snacks_Grown_Apple_Poisoned : Obj_Item_Weapon_ReagentContainers_Food_Snacks_Grown_Apple {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.seed = typeof(Obj_Item_Seeds_Poisonedappleseed);
		}

		public Obj_Item_Weapon_ReagentContainers_Food_Snacks_Grown_Apple_Poisoned ( dynamic newloc = null, int? new_potency = null ) : base( (object)(newloc), new_potency ) {
			
		}

		// Function from file: grown.dm
		public override bool add_juice( dynamic loc = null, int? potency = null ) {
			base.add_juice( (object)(loc), potency );
			this.reagents.add_reagent( "cyanide", Num13.Round( ( this.potency ??0) / 5, 1 ) + 1 );
			return false;
		}

	}

}