// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Structure_Sign_Bluecross : Obj_Structure_Sign {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.icon_state = "bluecross";
		}

		public Obj_Structure_Sign_Bluecross ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}