// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Weapon_Holo_Esword_Green : Obj_Item_Weapon_Holo_Esword {

		// Function from file: items.dm
		public Obj_Item_Weapon_Holo_Esword_Green ( dynamic loc = null ) : base( (object)(loc) ) {
			this.item_color = "green";
			return;
		}

	}

}