// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Weapon_Pickaxe_FourPick : Obj_Item_Weapon_Pickaxe {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.item_state = "syringe_0";
			this.digspeed = 20;
			this.excavation_amount = 4;
			this.drill_sound = "sound/items/Screwdriver.ogg";
			this.drill_verb = "delicately picking";
			this.w_class = 2;
			this.icon = "icons/obj/xenoarchaeology.dmi";
			this.icon_state = "pick4";
		}

		public Obj_Item_Weapon_Pickaxe_FourPick ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}