// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Clothing_Head_Snowman : Obj_Item_Clothing_Head {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.item_state = "snowman_h";
			this.flags_cover = 4;
			this.flags_inv = 15;
			this.icon_state = "snowman_h";
		}

		public Obj_Item_Clothing_Head_Snowman ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}