// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Structure_Displaycase_Gooncode : Obj_Structure_Displaycase {

		// Function from file: displaycase.dm
		public Obj_Structure_Displaycase_Gooncode ( dynamic loc = null ) : base( (object)(loc) ) {
			// Warning: Super call was HERE! If anything above HERE is needed by the super call, it might break!;
			this.occupant = new Obj_Item_Toy_Gooncode( this );
			this.locked = true;
			this.req_access = new ByTable(new object [] { GlobalVars.access_captain });
			this.update_icon();
			return;
		}

	}

}