// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Clothing_Under_Rank_Mechanic : Obj_Item_Clothing_Under_Rank {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.item_state = "mechanic";
			this._color = "mechanic";
			this.flags = 8448;
			this.icon_state = "mechanic";
		}

		public Obj_Item_Clothing_Under_Rank_Mechanic ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}