// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Structure_Closet_Crate_Engi_MeteorBreach : Obj_Structure_Closet_Crate_Engi {

		// Function from file: meteor_supply.dm
		public Obj_Structure_Closet_Crate_Engi_MeteorBreach ( dynamic loc = null ) : base( (object)(loc) ) {
			// Warning: Super call was HERE! If anything above HERE is needed by the super call, it might break!;
			new Obj_Item_Taperoll_Atmos( this );
			new Obj_Item_Taperoll_Atmos( this );
			new Obj_Item_Taperoll_Atmos( this );
			new Obj_Item_Weapon_Storage_Box_Foam( this );
			new Obj_Item_Weapon_Storage_Box_Foam( this );
			return;
		}

	}

}