// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Structure_Flora_Grass_Brown : Obj_Structure_Flora_Grass {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.icon_state = "snowgrass1bb";
		}

		// Function from file: flora.dm
		public Obj_Structure_Flora_Grass_Brown ( dynamic loc = null ) : base( (object)(loc) ) {
			// Warning: Super call was HERE! If anything above HERE is needed by the super call, it might break!;
			this.icon_state = "snowgrass" + Rand13.Int( 1, 3 ) + "bb";
			return;
		}

	}

}