// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Effect_Rune_Wall : Obj_Effect_Rune {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.cultist_name = "Form Shield";
			this.cultist_desc = "When invoked, makes the rune block passage. Can be invoked again to reverse this.";
			this.invocation = "Khari'd! Eske'te tannin!";
		}

		public Obj_Effect_Rune_Wall ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

		// Function from file: runes.dm
		public override void invoke( dynamic user = null ) {
			dynamic C = null;

			this.density = !this.density;
			((Ent_Static)user).visible_message( "<span class='warning'>" + user + " places their hands on " + this + ", and " + ( this.density ? "the air above it begins to shimmer" : "the shimmer above it fades" ) + ".</span>", "<span class='cultitalic'>You channel your life energy into " + this + ", " + ( this.density ? "preventing" : "allowing" ) + " passage above it.</span>" );

			if ( user is Mob_Living_Carbon ) {
				C = user;
				C.apply_damage( 2, "brute", Rand13.Pick(new object [] { "l_arm", "r_arm" }) );
			}
			return;
		}

		// Function from file: runes.dm
		public override double examine( dynamic user = null ) {
			base.examine( (object)(user) );

			if ( this.density ) {
				user.WriteMsg( "<span class='cultitalic'>There is a barely perceptible shimmering of the air above " + this + ".</span>" );
			}
			return 0;
		}

	}

}