// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Clothing_Suit_Space_Syndicate_Black_Green : Obj_Item_Clothing_Suit_Space_Syndicate_Black {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.item_state = "syndicate-black-green";
			this.icon_state = "syndicate-black-green";
		}

		public Obj_Item_Clothing_Suit_Space_Syndicate_Black_Green ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}