// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Clothing_Under_Darkholme : Obj_Item_Clothing_Under {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.item_state = "darkholme";
			this._color = "darkholme";
			this.icon_state = "darkholme";
		}

		public Obj_Item_Clothing_Under_Darkholme ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}