// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Structure_DockingPort_Destination_Syndicate : Obj_Structure_DockingPort_Destination {

		public Obj_Structure_DockingPort_Destination_Syndicate ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}