// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Clothing_Under_Rank_MaintenanceTech : Obj_Item_Clothing_Under_Rank {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.item_state = "mainttech";
			this._color = "mainttech";
			this.armor = new ByTable().Set( "melee", 0 ).Set( "bullet", 0 ).Set( "laser", 0 ).Set( "energy", 0 ).Set( "bomb", 0 ).Set( "bio", 0 ).Set( "rad", 10 );
			this.flags = 8448;
			this.icon_state = "mainttech";
		}

		public Obj_Item_Clothing_Under_Rank_MaintenanceTech ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}