// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Overlays_LegcuffLayer : Obj_Overlays {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.layer = -6;
		}

		public Obj_Overlays_LegcuffLayer ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}