// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_RobotParts_Head : Obj_Item_RobotParts {

		public dynamic flash1 = null;
		public dynamic flash2 = null;

		protected override void __FieldInit() {
			base.__FieldInit();

			this.icon_state = "head";
		}

		public Obj_Item_RobotParts_Head ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

		// Function from file: robot_parts.dm
		public override dynamic attackby( dynamic a = null, dynamic b = null, dynamic c = null ) {
			base.attackby( (object)(a), (object)(b), (object)(c) );

			if ( a is Obj_Item_Device_Flash ) {
				
				if ( Lang13.Bool( this.flash1 ) && Lang13.Bool( this.flash2 ) ) {
					GlobalFuncs.to_chat( b, "<span class='notice'>You have already inserted the eyes!</span>" );
					return null;
				} else if ( Lang13.Bool( this.flash1 ) ) {
					
					if ( Lang13.Bool( b.drop_item( a, this ) ) ) {
						this.flash2 = a;
						GlobalFuncs.to_chat( b, "<span class='notice'>You insert the flash into the eye socket!</span>" );
					}
				} else if ( Lang13.Bool( b.drop_item( a, this ) ) ) {
					this.flash1 = a;
					GlobalFuncs.to_chat( b, "<span class='notice'>You insert the flash into the eye socket!</span>" );
				}
			} else if ( a is Obj_Item_Weapon_StockParts_Manipulator ) {
				
				if ( Lang13.Bool( b.drop_item( a ) ) ) {
					GlobalFuncs.to_chat( b, "<span class='notice'>You install some manipulators and modify the head, creating a functional spider-bot!</span>" );
					new Mob_Living_SimpleAnimal_Spiderbot( GlobalFuncs.get_turf( this.loc ) );
					GlobalFuncs.qdel( a );
					a = null;
					GlobalFuncs.qdel( this );
					return null;
				}
			}
			return null;
		}

	}

}