// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Weapon_Resonator : Obj_Item_Weapon {

		public bool cooldown = false;

		protected override void __FieldInit() {
			base.__FieldInit();

			this.item_state = "resonator";
			this.force = 10;
			this.throwforce = 10;
			this.icon_state = "resonator";
		}

		public Obj_Item_Weapon_Resonator ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

		// Function from file: mine_items.dm
		public override bool afterattack( dynamic A = null, dynamic user = null, bool? flag = null, dynamic _params = null, bool? struggle = null ) {
			
			if ( Lang13.Bool( user.contents.Contains( A ) ) ) {
				return false;
			}

			if ( flag == true ) {
				this.CreateResonance( A, user );
			}
			return false;
		}

		// Function from file: mine_items.dm
		public override dynamic attack_self( dynamic user = null, dynamic flag = null, bool? emp = null ) {
			this.CreateResonance( this, user );
			base.attack_self( (object)(user), (object)(flag), emp );
			return null;
		}

		// Function from file: mine_items.dm
		public void CreateResonance( dynamic target = null, dynamic creator = null ) {
			Obj_Effect_Resonance R = null;

			
			if ( ( this.cooldown ?1:0) <= 0 ) {
				GlobalFuncs.playsound( GlobalFuncs.get_turf( this ), "sound/effects/stealthoff.ogg", 50, 1 );
				R = new Obj_Effect_Resonance( GlobalFuncs.get_turf( target ) );
				R.creator = creator;
				this.cooldown = true;
				Task13.Schedule( 20, (Task13.Closure)(() => {
					this.cooldown = false;
					return;
				}));
			}
			return;
		}

	}

}