// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Device_Radio_Headset_HeadsetCent_Alt : Obj_Item_Device_Radio_Headset_HeadsetCent {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.flags = 1024;
			this.item_state = "cent_headset_alt";
			this.icon_state = "cent_headset_alt";
		}

		public Obj_Item_Device_Radio_Headset_HeadsetCent_Alt ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}