// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Clothing_Shoes_Sneakers_Black_Redcoat : Obj_Item_Clothing_Shoes_Sneakers_Black {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.item_color = "redcoat";
		}

		public Obj_Item_Clothing_Shoes_Sneakers_Black_Redcoat ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}