// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Clothing_Mask_Cigarette_Rollie_Trippy : Obj_Item_Clothing_Mask_Cigarette_Rollie {

		// Function from file: cigs_lighters.dm
		public Obj_Item_Clothing_Mask_Cigarette_Rollie_Trippy ( dynamic loc = null ) : base( (object)(loc) ) {
			// Warning: Super call was HERE! If anything above HERE is needed by the super call, it might break!;
			this.reagents.add_reagent( "mushroomhallucinogen", 50 );
			this.f_light();
			return;
		}

	}

}