// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Machinery_Camera_Xray : Obj_Machinery_Camera {

		// Function from file: presets.dm
		public Obj_Machinery_Camera_Xray ( dynamic loc = null ) : base( (object)(loc) ) {
			// Warning: Super call was HERE! If anything above HERE is needed by the super call, it might break!;
			this.upgradeXRay();
			this.update_icon();
			return;
		}

	}

}