// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Effect_ProcHolder_Spell_AoeTurf_FlickerLights : Obj_Effect_ProcHolder_Spell_AoeTurf {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.charge_max = 300;
			this.clothes_req = 0;
			this.range = 14;
		}

		public Obj_Effect_ProcHolder_Spell_AoeTurf_FlickerLights ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

		// Function from file: statue.dm
		public override bool cast( dynamic targets = null, dynamic thearea = null, dynamic user = null ) {
			thearea = thearea ?? Task13.User;

			dynamic T = null;
			Obj_Machinery_Light L = null;

			
			foreach (dynamic _b in Lang13.Enumerate( targets )) {
				T = _b;
				

				foreach (dynamic _a in Lang13.Enumerate( T, typeof(Obj_Machinery_Light) )) {
					L = _a;
					
					L.flicker();
				}
			}
			return false;
		}

	}

}