// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Obj_Item_Weapon_RcdAmmo_Large : Obj_Item_Weapon_RcdAmmo {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.origin_tech = "materials=4";
			this.materials = new ByTable().Set( "$metal", 12000 ).Set( "$glass", 8000 );
			this.ammoamt = 160;
		}

		public Obj_Item_Weapon_RcdAmmo_Large ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}