// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Tile_Simulated_Shuttle_Plating_Vox : Tile_Simulated_Shuttle_Plating {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.nitrogen = 103.93377685546875;
		}

		public Tile_Simulated_Shuttle_Plating_Vox ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}