// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Zone_Start : Zone {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.requires_power = false;
			this.lighting_use_dynamic = false;
			this.icon_state = "start";
		}

		public Zone_Start ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}