// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Zone_Medical_Chemistry : Zone_Medical {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.icon_state = "chem";
		}

		public Zone_Medical_Chemistry ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}