// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Zone_TurretProtected_Tcomeast : Zone_TurretProtected {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.icon_state = "tcomsateast";
		}

		public Zone_TurretProtected_Tcomeast ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}