// FILE AUTOGENERATED BY SOMNIUM13.

using System;
using Somnium.Engine.ByImpl;

namespace Somnium.Game {
	class Zone_Shuttle_Transport1_Centcom : Zone_Shuttle_Transport1 {

		protected override void __FieldInit() {
			base.__FieldInit();

			this.icon_state = "shuttle";
		}

		public Zone_Shuttle_Transport1_Centcom ( dynamic loc = null ) : base( (object)(loc) ) {
			
		}

	}

}